Repository GoodwayGroup/lib-hapi-good-tracer, pull requests merged in 2020-08, with the labels that each got.

#10 docs: correct repo url
  .chglog/config.yml
  package.json
Labels: documentation

#17 chore(deps): update dependencies
  package-lock.json
  package.json
Labels: techdebt

#21 chore(renovate): add config
  .github/renovate.json
Labels: chore
